name: ASP.NET Core CI Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release
      
    - name: Test with dotnet
      run: dotnet test --verbosity normal --collect:"XPlat Code Coverage"
      
#     - name: Copy Coverage To Predictable Location
#       run: cp ./coverage/**/coverage.cobertura.xml coverage.cobertura.xml

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.2.0
      with:
        filename: '**/coverage.cobertura.xml'
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'
    - name: Publish with dotnet
      run: dotnet publish
